spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: validate
            generate-ddl: true
            show-sql : true

    datasource:
        url: jdbc:mysql://mysql:3306/AxisOmniChannel
        username: demo_user
        password: root
        driver-class-name: com.mysql.jdbc.Driver